sudo: required
services:
  - docker

before_install:
  - docker build -t sifat-cefalo/docker-travis-learning -f Dockerfile.dev .

script:
  - docker run sifat-cefalo/docker-travis-learning npm start test -- --coverage
