name: Test with github actions
on:
  push:
    branches: [ main ]
jobs:
  Build docker image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build -t sifat-cefalo/docker-travis-learning -f Dockerfile.dev .