name: Test with github actions
on:
  push:
    branches: [ main ]
jobs:
  Build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: |
          docker build -t ${{ secrets.IMAGE_TAG_NAME }} -f Dockerfile.dev .
          docker run -e CI=true ${{ secrets.IMAGE_TAG_NAME }} npm test -- --coverage
